### ISSUE TITLE
Create Video Presentation for the report

### ISSUE THREAD

**Issue by cmango7** [cterzis1435/Tutorial-12-Group-1#39]
Create your section of the Video Presentation

**Comment by cmango7** [comment]
Completed my video and sent to Greg to edit

**Comment by M-Santa** [comment]
Also completed my video and sent to Greg to edit

**Comment by Djacob02** [comment]
Completed my video and sent to Greg to edit

**Comment by GregMouawad** [comment]
Ive edited the video
